name: Build
on: push
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [8, 10, 12, 13]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn run build
      - run: yarn run type
      - run: yarn run coverage
      - run: yarn run eslint
  integrate:
    name: Integrations
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --ignore-engines --frozen-lockfile
      - run: yarn run build
      - run: yarn run type
      - run: yarn run test:int:pass
      - run: yarn run test:int:fail
